### ISSUE TITLE
OCaml class interface for prepared SQL statements

### ISSUE THREAD

**Issue by elfring** [mmottl/postgresql-ocaml#13]
The class "connection" provides a few methods which deal with prepared SQL statements. I imagine that it will be useful to map this software area to an improved class hierarchy.
How do you think about to add a method like "create_prepared_statement" which will generate object instances instead of distinguishing SQL statements by [the parameter "stm_name" of the method "prepare"](https://github.com/mmottl/postgresql-ocaml/blob/dac9d9559c29caaca7abfb7e4c927fa25f2f7397/lib/postgresql.mli#L595 "SQL query preparation")?

**Comment by mmottl** [comment]
Classes/objects actually only exist in these bindings for historical reasons.  I'm sure the author of the first version of these bindings would now also prefer the module system.  Maybe it would be better in the longer term to rewrite the library using the module system only.  This shouldn't be too hard, but I don't have time for this right now.

I agree it would make things a little safer if, instead of using a "string" to refer to a prepared statement, we had an abstract type.  This would make it impossible to use a string that was never used to prepare a statement.  But I don't want to break too much code, and the added benefit is presumably small.  It is easy enough for users to introduce their own abstraction for dealing with prepared statements more safely.
