### ISSUE TITLE
Improve use of caml_alloc_final on results

### ISSUE THREAD

**Issue by alainfrisch** [mmottl/postgresql-ocaml#22]
Two suggested improvements on:

https://github.com/mmottl/postgresql-ocaml/blob/0f15dd4ac80d47d940f70ad58a71821bbb8a3e87/src/postgresql_stubs.c#L493

1. The implementation of caml_alloc_final in the OCaml runtime system needs to wrap the finalizer into a full "custom operations" struct.  This is cached, but the lookup in the cache is a linear scan.  So a program that uses a lot of caml_alloc_final with different finalization functions can get some overhead.  It is better to use directly caml_alloc_custom in user code.

2. The ratio 1/500 seems a bit high.  It implies a major cycle every 500 allocations of a result.    I don't know how much of an overhead a "result" represents in the postgresql client library, but if it's not too high, it might be good to reduce the ratio.  One could also expose an explicit function to release a result value explicitly (before the GC collects the OCaml wrapper).

**Comment by mmottl** [comment]
Thanks for the hint, I have improved the situation.  Since most result values are likely only a few hundred bytes and given the available memory of modern machines, I have considerably increased the number of allocations before each major cycle to 100_000.  My other bindings will also soon be changed to avoid `caml_alloc_final`.
